import { Inter } from "next/font/google";
import "./globals.css";
// import Image from "next/image";
// import ManojTittle from "./.././public/ProjectPageImage/ManojTittle.png";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* <link rel="icon" href="/ManojTittle.png" /> */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
